name: Build and Deploy to /docs (GitHub Pages)

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Vite app
        run: npm run build

      - name: Remove old docs (except README.md)
        run: |
          mkdir -p docs
          find docs/* ! -name 'README.md' -exec rm -rf {} +

      - name: Copy dist to docs
        run: |
          if [ ! -d dist ]; then echo "dist/ does not exist!"; exit 1; fi
          cp -r dist/* docs/

      - name: Commit and push changes to docs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: deploy to docs for GitHub Pages"
          branch: main
          file_pattern: docs/*

      - name: Show deployment info
        run: echo "Your site will be live at https://phamkitty.github.io/Portfolio"
