name: Build and Deploy to /docs (GitHub Pages)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Vite app
        run: npm run build

      - name: Remove old docs (except README)
        run: |
          shopt -s extglob
          rm -rf docs/!(README.md)

      - name: Copy dist to docs
        run: |
          mkdir -p docs
          cp -r dist/* docs/

      - name: Commit and push changes to docs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: deploy to docs for GitHub Pages"
          branch: main
          file_pattern: docs/*

      - name: Show deployment info
        run: echo "Your site will be live at https://phamkitty.github.io/Portfolio"
